config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'static_pages#home'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :gossips do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :like, as: :likeable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes, as: :likeable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :username,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  has_many :gossips
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.gossip_id = params[:gossip_id]
    @comment.save
    redirect_to gossip_path(@comment.gossip)
  end

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to gossip_path(@comment.gossip)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to gossips_path(@comment.gossip)
  end

  def comment_params
    params.require(:comment).permit(:anonymous_commentor, :content)
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossip = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end
=begin
  def create
    @gossip = Gossip.create(title: params["gossip"]["title"], content: params["gossip"]["content"])
    redirect_to @gossip
  end
=end

  def create
    @gossip = Gossip.new(gossip_params)
    if logged_in?
      @gossip.save
      redirect_to @gossip
    else
      flash.now[:alert] = "You must be logged in !"
      redirect_to '/'
    end
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @comment.gossip_id = @gossip.id
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title,:content)
    @gossip.update(gossip_params)
    redirect_to @gossip
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.delete
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to '/'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to '/'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def contact
  end

  def team
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Your Gossip account has been created !"
      redirect_to '/'
    else
      flash.now[:alert] = "Your Gossip account creation has failed !"
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1> Edit a comment</h1>
<div style='width: 80%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for [@gossip, @comment] do |f| %>
  <%= label_tag 'Comment:' %>
  <%= f.text_area :content, class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= f.submit "Edit the comment", class: "btn btn-success"  %>
<% end %>

app/views/gossips/_comment.html.erb
<div class="card-comment">
<div class="card w-50">
 <div class="card-body">
   <h5 class="card-title"><%= user.username %></h5>
   <p class="card-text"><%= comment.content %></p>
   <p class='card-time'>Created @<%= comment.created_at %></p>
    <p class ='card-time'>Updated @<%= comment.updated_at %></p>
     <a href="<%=edit_gossip_comment_path(@gossip.id,comment.id)%>" class="btn btn-primary">Edit</a>
     <a href="<%= gossip_comment_path(@gossip.id,comment.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
 </div>
</div>
</div>

app/views/gossips/edit.html.erb
<div style='width: 80%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for @gossip do |f| %>
  <%= label_tag 'Title:' %>
  <%= f.text_field :title, placeholder: 'Your title...', class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= label_tag 'Content:' %>
  <%= f.text_area :content, placeholder: 'Your content...', class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= f.submit "Edit the Gossip", class: "btn btn-success"  %>
<% end %>

app/views/gossips/index.html.erb
<h1>All the Gossips</h1><br>
<% @gossip.each do |gossip, user| %>
<div class="card-box">
<div class="card border-light mb-3" style="max-width: 18rem;">
<div class="card-header"><a href="/gossips/<%=gossip.id%>"> Gossip n°<%=gossip.id%></a></div>
<div class="card-body">
 <h5 class="card-title"><%= user.username %></h5>
 <p class="card-text"><%= gossip.content%></p>
 <a href="<%= edit_gossip_path(gossip.id)%>" class="btn btn-primary">Edit</a>
 <a href="<%= gossip_path(gossip.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
</div>
</div>
</div>
<% end %>

app/views/gossips/new.html.erb
<h1>Write your own gossip</h1>
<div style='width: 20%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for @gossip do |f| %>
  <%= label_tag 'Title:' %>
  <%= f.text_field :title, placeholder: 'Your title...', class: "form-control", id: "formGroupExampleInput2" %>
  <br /><br />
  <%= label_tag 'Content:' %>
  <%= f.text_area :content, placeholder: 'Your content...', class: "form-control", id: "formGroupExampleInput2" %>
  <br /><br />
  <%= f.submit "Add the Gossip", class: "btn btn-success"  %>
<% end %>

app/views/gossips/show.html.erb
<h1>GOSSIP <%=params[:id]%></h1>
  <p>
    <div class="card-box">
      <div class="card border-light mb-3" style="max-width: 18rem;">
        <div class="card-header"><%=@gossip.title%></div>
        <div class="card-body">
          <p class="card-text"><%= @gossip.content%></p>
          <p class="card-text"><%= @user.username%></p>
          <p class="card-time">Created @<%= @gossip.created_at%></p>
          <p class="card-time">Updated @<%= @gossip.updated_at%></p>
          <p>Comments (<%= @gossip.comments.size %>)</p>
        </div>
      </div>
    </div>
    <h2> Comments : </h2>
    <%= render partial: 'gossips/comment', collection: @gossip.comments.reverse%>
  <%= render partial: 'layouts/form' %>

app/views/layouts/_form.html.erb
<div class='formulix' style='width: 80%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for [@gossip, @comment] do |f| %>
  <%= label_tag 'Author:' %>
  <%= f.text_field :anonymous_commentor, placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= label_tag 'Comment:' %>
  <%= f.text_area :content, placeholder: 'Your comment...', class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= f.submit "Add a comment", class: "btn btn-success"  %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="/gossips">Index<span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="/gossips/new">Create a Gossip</a>
        <a class="nav-item nav-link" href="/team">Team</a>
        <a class="nav-item nav-link disabled" href="/contact">Contact</a>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>If you have any questions click <a href="https://www.facebook.com/ysaline.wizzy">here</a> !</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <p class='button'><%= link_to "Log out", logout_path, method: :delete, class: "btn btn-lg btn-primary" %></p>
<% else %>
 <p class='button'><%= link_to "Log in", '/login', class: "btn btn-lg btn-primary" %></p>
<% end %>

<h1>Welcome !</h1>

app/views/static_pages/team.html.erb
<h1>Team</h1>
<h5>This website has been released by THP Nice</h5>
<p>
  <ul>
    <li><a href='https://github.com/ysalien'>Ysaline</a></li>
    <li><a href='https://github.com/Natdenice'>Nat</a></li>
    <li><a href='https://github.com/TomacTh'>Tom</a></li>
    <li><a href='https://github.com/NikitaVasilev'>Nikita</a></li>
    <li><a href='https://github.com/tutus06'>Arthur</a></li></ul>
    </p>

app/views/users/new.html.erb
<h1> Create an account</h1>
<div class='formulix' style='width: 20%; margin-left: 30px; margin-top: 30px;'>
  <%= form_for @user do |f| %>
  <%= label_tag 'Username :' %>
  <%= f.text_field :username, placeholder: "Your username..", class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= label_tag 'Email adress :' %>
  <%= f.text_field :email, placeholder: "Your email...", class: "form-control", id: "formGroupExampleInput2" %>
  <br><br>
  <%= label_tag 'Password :' %>
  <%= f.text_field :password, placeholder: "Your password...", class: "form-control", type: "password", id: "formGroupExampleInput2" %>
  <br><br>
  <%= f.submit "Create an account", class: "btn btn-success"  %>
<% end %>